### ISSUE TITLE
"Exception in thread Thread-6:ack-perl/ptop"-Error

### ISSUE THREAD

**Issue by niko** [black-perl/ptop#9]
in /usr/lib/python3.4/threading.py line 920

TypeError: non-empty format string passed to object.__format__

ptop 0.0.6 Python 3.4.3 on Arch linux.

**Comment by black-perl** [comment]
#8  addresses the issue, need to add Python3 support.

**Comment by niko** [comment]
Works like a charm when installed using "sudo pip2.7 install ptop". Thanks.

**Comment by black-perl** [comment]
yeah sure !
